services:
  server:
    build:
      context: .
      dockerfile: ./apps/node.Dockerfile
      target: dev
      args:
        APP: server
    environment:
      MONGODB_URL: mongodb://mongodb:27017/auth
      PROVIDERS_CONFIG_FILE: /providers.yaml
      SESSION_COOKIE_HTTPONLY: "false"
      SESSION_SALT: mq9hDxBVDbspDR6n
      SESSION_SAME_SITE: lax
      SESSION_SECRET: averylogphrasebiggerthanthirtytwochars
    volumes:
      - ./apps:/home/node/root/apps
      - ./dev/providers.yaml:/providers.yaml
      - ./proto:/home/node/root/proto
    ports:
      - 9000:3000
    links:
      - gobblr
      - mongodb
      - provider_github
    restart: on-failure

  #############
  # Providers #
  #############
  provider_github:
    build:
      context: .
      dockerfile: ./apps/node.Dockerfile
      target: dev
      args:
        APP: provider_github
    environment:
      CLIENT_ID: ${GITHUB_CLIENT_ID}
      CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      CALLBACK_URL: http://localhost:9000/v1/providers/github/login/callback
      SCOPES: repo
    volumes:
      - ./apps:/home/node/root/apps
      - ./proto:/home/node/root/proto
    ports:
      - 3000:3000
    restart: on-failure

  ########################
  # Third-party services #
  ########################
  gobblr:
    image: ghcr.io/mrsimonemms/gobblr
    environment:
      GOBBLR_CONNECTION_URI: mongodb://mongodb:27017/gobblr
    ports:
      - 4001:5670
    links:
      - mongodb
    volumes:
      - ./dev/data:/app/data
    restart: on-failure
    command: db mongodb --run

  mongodb:
    image: mongo:8.0
    ports:
      - 4000:27017
