services:
  server:
    build:
      context: .
      dockerfile: ./apps/golang.Dockerfile
      target: dev
      args:
        APP: server
    environment:
      CONFIG: config.example.yaml
      CONFIG_COOKIE_KEY: RHXV1WDKGoHbcQHy6+RrmqrrznAXixkN8jQBRH4gkxU= # Randomly generated code - openssl rand -base64 32
      CONFIG_ENCRYPTION_KEY: this-is-some-secret-encryption-string
      CONFIG_JWT_KEY: q1w2e3r4
      LOG_LEVEL: ${LOG_LEVEL-trace}
    volumes:
      - ./apps:/go/root/apps
    ports:
      - 9000:3000
    links:
      - gobblr
      - mongodb
      - mysql
      - provider-github
      - provider-gitlab
    depends_on:
      provider-github:
        condition: service_healthy
      provider-gitlab:
        condition: service_healthy
    restart: on-failure
    command: air -build.args_bin run -build.pre_cmd="go generate ./..." -build.exclude_dir docs
    healthcheck:
      test: curl --fail http://localhost:3000/livez || exit 1
      interval: 10s
      timeout: 1s
      retries: 5
      start_period: 10s

  #############
  # Providers #
  #############
  provider-github:
    build:
      context: .
      dockerfile: ./apps/node-grpc.Dockerfile
      target: dev
      args:
        APP: provider-github
    environment:
      CLIENT_ID: ${GITHUB_CLIENT_ID}
      CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      CALLBACK_URL: http://localhost:9000/v1/providers/github/login/callback
      SCOPES: repo
    volumes:
      - ./apps:/home/node/root/apps
      - ./proto:/home/node/root/proto
      - ./packages/js-sdk:/home/node/root/apps/provider-github/node_modules/@opensesame-cloud/js-sdk
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:3000"]
      start_period: 10s
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - js-sdk

  provider-gitlab:
    build:
      context: .
      dockerfile: ./apps/node-grpc.Dockerfile
      target: dev
      args:
        APP: provider-gitlab
    environment:
      CLIENT_ID: ${GITLAB_CLIENT_ID}
      CLIENT_SECRET: ${GITLAB_CLIENT_SECRET}
      CALLBACK_URL: http://localhost:9000/v1/providers/gitlab/login/callback
    volumes:
      - ./apps:/home/node/root/apps
      - ./proto:/home/node/root/proto
      - ./packages/js-sdk:/home/node/root/apps/provider-gitlab/node_modules/@opensesame-cloud/js-sdk
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:3000"]
      start_period: 10s
    ports:
      - 3001:3000
    restart: on-failure
    depends_on:
      - js-sdk

  js-sdk:
    image: node:lts
    working_dir: /home/node/sdk
    command: npm run build -- --watch
    volumes:
      - ./packages/js-sdk:/home/node/sdk
    user: node
    restart: on-failure

  ########################
  # Third-party services #
  ########################
  gobblr:
    image: ghcr.io/mrsimonemms/gobblr
    environment:
      GOBBLR_CONNECTION_URI: mongodb://mongodb:27017
      GOBBLR_DATABASE: auth
    ports:
      - 4001:5670
    links:
      - mongodb
    volumes:
      - ./dev/data:/app/data
    restart: on-failure
    command: db mongodb --run

  mongodb:
    image: mongo:8.0
    ports:
      - 4000:27017

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: app
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_PASSWORD: password
      MYSQL_USER: app
    ports:
      - 4002:3306
    restart: on-failure
