services:
  server:
    build:
      context: .
      dockerfile: ./apps/golang.Dockerfile
      target: dev
      args:
        APP: server
    environment:
      CONFIG: config.example.yaml
      LOG_LEVEL: ${LOG_LEVEL-trace}
    volumes:
      - ./apps:/go/root/apps
    ports:
      - 9000:3000
    links:
      - gobblr
      - mongodb
    restart: on-failure
    command: air -build.args_bin run

  ########################
  # Third-party services #
  ########################
  gobblr:
    image: ghcr.io/mrsimonemms/gobblr
    environment:
      GOBBLR_CONNECTION_URI: mongodb://mongodb:27017/auth
    ports:
      - 4001:5670
    links:
      - mongodb
    volumes:
      - ./dev/data:/app/data
    restart: on-failure
    command: db mongodb --run

  mongodb:
    image: mongo:8.0
    ports:
      - 4000:27017
