database:
  type: sql
  sql:
    type: mysql
    dsn: app:password@tcp(mysql:3306)/app?charset=utf8mb4&parseTime=True&loc=Local
  mongodb:
    connectionURI: mongodb://mongodb:27017
    database: auth
encryption:
  key: "{{ .CONFIG_ENCRYPTION_KEY }}"
jwt:
  key: "{{ .CONFIG_JWT_KEY }}"
providers:
  - id: github
    name: GitHub
    address: provider-github:3000
  - id: gitlab
    name: GitLab
    address: provider-gitlab:3000
server:
  port: 3000
  cookie:
    key: "{{ .CONFIG_COOKIE_KEY }}"
